<?php

use Phalcon\Forms\Form;
use Phalcon\Forms\Element\Text;
use Phalcon\Validation\Validator\StringLength;

$form = new Form();

$form->add(new Text('name'));

// $name->addValidator(
//     new StringLength(
//         [
//             'min'            => 10,
//             'messageMinimum' => 'The name is too short',
//         ]
//     )
// );

$form->add(new Text('lastName'));

$form->add(new Text('email'));
?>

<form method='post'>

    <p>
        <label>
            Name
        </label>

        <?php echo $form->render('name'); ?>
    </p>

    <p>
        <label>
            Last Name
        </label>

        <?php echo $form->render('lastName'); ?>
    </p>

    <p>
        <label>
            Email
        </label>

        <?php echo $form->render('email'); ?>
    </p>

    <p>
        <input type='submit' value='Save' />
    </p>

</form>